theme: jekyll-theme-slate
title: My Projects Portfolio
description: My projects on various data science skills!
url-pretty: "MyWebsite.com"
social-network-links:
  email: "karan433155@gmail.com" 
page-col: "#FFFFFF"
share-links-active:
  twitter: true
  facebook: true
  linkedin: true
